projet_multimedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('', include('traitement_app.urls')),
	path('admin/', admin.site.urls),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

traitement_app/urls.py
from django.urls import path

from . import views

app_name = 'traitement_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('image/', views.image, name='image'),
    path('ResNet101/', views.ResNet101, name='ResNet101'),
    
]

traitement_app/models.py
from django.db import models

# Create your models here.

traitement_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
import base64
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
import numpy as np
from matplotlib import pyplot as plt
from PIL import Image
import tensorflow as tf
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as viz_utils






# Loading ResNet
GLOBAL_PATH = 'traitement_app/'
PATH_TO_MODEL_DIR_2 = GLOBAL_PATH + 'exported-models/my_faster_rcnn'
PATH_TO_SAVED_MODEL_2 = PATH_TO_MODEL_DIR_2 + "/saved_model"

# Load saved model and build the detection function
model_2 = tf.saved_model.load(PATH_TO_SAVED_MODEL_2)
detect_fn_2 = model_2.signatures['serving_default']


PATH_TO_LABELS = GLOBAL_PATH + 'annotations/label_map.pbtxt'
category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS, use_display_name=True)

def index(request):
    if request.method == 'GET':
        return render(request, 'traitement_app/index.html')
    else:
        if request.is_ajax():
            img_data = request.POST['img_data']
            dec = base64.decodebytes(bytes(img_data, 'utf-8'))
            with open("traitement_app/static/traitement_app/images/image.png", "wb") as fic:
                fic.write(dec)
            return JsonResponse({'message': 'operation réussi'}, status=200)

def image(request):
    return render(request, 'traitement_app/images.html')

def load_image_into_numpy_array(path):
    """Load an image from file into a numpy array.

    Puts image into numpy array to feed into tensorflow graph.
    Note that by convention we put it into a numpy array with shape
    (height, width, channels), where channels=3 for RGB.

    Args:
      path: the file path to the image

    Returns:
      uint8 numpy array with shape (img_height, img_width, 3)
    """
    return np.array(Image.open(path))



def ResNet101(request):
    image_path = 'traitement_app/static/traitement_app/images/image.png'

    image_np = load_image_into_numpy_array(image_path)
    
    # The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
    input_tensor = tf.convert_to_tensor(image_np)
    # The model expects a batch of images, so add an axis with `tf.newaxis`.
    input_tensor = input_tensor[tf.newaxis, ...]

    detections = detect_fn_2(input_tensor)

    # All outputs are batches tensors.
    # Convert to numpy arrays, and take index [0] to remove the batch dimension.
    # We're only interested in the first num_detections.
    num_detections = int(detections.pop('num_detections'))
    detections = {key: value[0, :num_detections].numpy()
                  for key, value in detections.items()}
    detections['num_detections'] = num_detections

    # detection_classes should be ints.
    detections['detection_classes'] = detections['detection_classes'].astype(np.int64)

    image_np_with_detections = image_np.copy()

    viz_utils.visualize_boxes_and_labels_on_image_array(
          image_np_with_detections,
          detections['detection_boxes'],
          detections['detection_classes'],
          detections['detection_scores'],
          category_index,
          use_normalized_coordinates=True,
          max_boxes_to_draw=200,
          min_score_thresh=.50,
          agnostic_mode=False)

    plt.figure(figsize=(10, 10), dpi = 80)
    plt.axis('off')
    plt.imshow(image_np_with_detections) 
    plt.savefig('traitement_app/static/traitement_app/images/image.png')
    return render(request, 'traitement_app/images.html')

traitement_app/templates/traitement_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    
    {% block style %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'traitement_app/bootstrap-4.0.0-dist/css/bootstrap.min.css' %}">
    <script src="{% static 'traitement_app/jquery.min.js' %}"></script>
    <script src="{% static 'traitement_app/popper.min.js' %}"></script>
    <script src="{% static 'traitement_app/bootstrap-4.0.0-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'traitement_app/moment.min.js' %}"></script>
    <script src="{% static 'traitement_app/sweetalert.min.js' %}"></script>

    <link rel="stylesheet" type="text/css"
        href="{% static 'traitement_app/DataTables/DataTables-1.10.20/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css"
        href="{% static 'traitement_app/DataTables/Select-1.3.1/css/select.bootstrap4.min.css' %}">

    <script src="{% static 'traitement_app/DataTables/DataTables-1.10.20/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'traitement_app/DataTables/DataTables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'traitement_app/DataTables/Select-1.3.1/js/dataTables.select.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'traitement_app/select2.min.css' %}">
    <script src="{% static 'traitement_app/select2.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'traitement_app/print.min.css' %}">
    <script src="{% static 'traitement_app/print.min.js' %}"></script>

    <script>
        function openAttachment() {
            document.getElementById('attachment').click();
        }
    
        function encodeImageFileAsURL(element) {
            var file = element.files[0];
            var reader = new FileReader();
            reader.onloadend = function() {
                $.ajax({
                type: 'POST',
                url: "{% url 'traitement_app:index'%}",
                data: {
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    img_data: reader.result.split(',')[1],
                },
                success: function (response) {
                    location.replace("/image");
                },
                error: function (response) {
                    swal("Erreur!", "Une erreur s'est produite.", "error");
                }
            });
            }
            reader.readAsDataURL(file);
        }
    </script>

    {% block script %}{% endblock %}
</head>

<body>
    {% csrf_token %}

    {% block navbar %}
    <nav class="navbar navbar-expand-sm bg-light navbar-dar">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" onclick="openAttachment()" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Charger une image
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Détection d'objets
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'traitement_app:MobileNet' %}">MobileNet</a>
                      <a class="dropdown-item" href="{% url 'traitement_app:ResNet101' %}">ResNet101</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <input type="file" class="file" id="attachment" style="display: none;" onchange="encodeImageFileAsURL(this)" accept=".jpg, .jpeg, .png"/>
    {% endblock %}
 
    {% block main %}
    {% endblock %}


</body>

</html>

traitement_app/templates/traitement_app/base2.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    

<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 265px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #33FFC3;
  overflow-x: hidden;
  padding-top: 200px;
}
.sidenav2 {
  height: 100%;
  width: 265px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #33FFE8 ; 
  
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #0D5054;
}
.field_set {
    margin-top: 20px;
    border: 2px black solid;
    padding: 4px;
	text-align: center;
}

.main {
  margin-left: 265px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
{% block style %}{% endblock %}

<link rel="stylesheet" type="text/css" href="{% static 'traitement_app/bootstrap-4.0.0-dist/css/bootstrap.min.css' %}">
    <script src="{% static 'traitement_app/jquery.min.js' %}"></script>
    <script src="{% static 'traitement_app/popper.min.js' %}"></script>
    <script src="{% static 'traitement_app/bootstrap-4.0.0-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'traitement_app/moment.min.js' %}"></script>
    <script src="{% static 'traitement_app/sweetalert.min.js' %}"></script>

    <link rel="stylesheet" type="text/css"
        href="{% static 'traitement_app/DataTables/DataTables-1.10.20/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css"
        href="{% static 'traitement_app/DataTables/Select-1.3.1/css/select.bootstrap4.min.css' %}">

    <script src="{% static 'traitement_app/DataTables/DataTables-1.10.20/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'traitement_app/DataTables/DataTables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'traitement_app/DataTables/Select-1.3.1/js/dataTables.select.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'traitement_app/select2.min.css' %}">
    <script src="{% static 'traitement_app/select2.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'traitement_app/print.min.css' %}">
    <script src="{% static 'traitement_app/print.min.js' %}"></script>

    <script>
        function openAttachment() {
            document.getElementById('attachment').click();
        }
    
        function encodeImageFileAsURL(element) {
            var file = element.files[0];
            var reader = new FileReader();
            reader.onloadend = function() {
                $.ajax({
                type: 'POST',
                url: "{% url 'traitement_app:index'%}",
                data: {
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    img_data: reader.result.split(',')[1],
                },
                success: function (response) {
                    location.replace("/image");
                },
                error: function (response) {
                    swal("Erreur!", "Une erreur s'est produite.", "error");
                }
            });
            }
            reader.readAsDataURL(file);
        }
    </script>
{% block script %}{% endblock %}


</head>
<body>
{% csrf_token %}
{% block sidebar %}
<div class="sidenav">
  
 <a class=" mx-auto btn btn-light" href="#" onclick="openAttachment()"  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Charger une image
 </a>
 <a class="mx-auto my-5 btn btn-light" href="{% url 'traitement_app:ResNet101' %} " role="button">Detecter</a>


</div>
<input type="file" class="file" id="attachment" style="display: none;" onchange="encodeImageFileAsURL(this)" accept=".jpg, .jpeg, .png"/>
{% endblock %}

<div class="main">

 <div class="field_set">
  <h2 >Detection d'objets presents dans une images</h2>
 </div>

  
  
  <div>
  {% block main %}
	
  {% endblock %}
  </div>
  
</div>
   
</body>
</html> 

traitement_app/templates/traitement_app/base3.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    

<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 265px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #33FFC3;
  overflow-x: hidden;
  padding-top: 200px;
}
.sidenav2 {
  height: 100%;
  width: 265px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #33FFE8 ; 
  
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  
}

.sidenav a:hover {
  color: #0D5054;
}
.field_set {
    margin-top: 20px;
    border: 2px black solid;
    padding: 4px;
	text-align: center;
}

.main {
  margin-left: 265px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
{% block style %}{% endblock %}

<link rel="stylesheet" type="text/css" href="{% static 'traitement_app/bootstrap-4.0.0-dist/css/bootstrap.min.css' %}">
    <script src="{% static 'traitement_app/jquery.min.js' %}"></script>
    <script src="{% static 'traitement_app/popper.min.js' %}"></script>
    <script src="{% static 'traitement_app/bootstrap-4.0.0-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'traitement_app/moment.min.js' %}"></script>
    <script src="{% static 'traitement_app/sweetalert.min.js' %}"></script>

    <link rel="stylesheet" type="text/css"
        href="{% static 'traitement_app/DataTables/DataTables-1.10.20/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css"
        href="{% static 'traitement_app/DataTables/Select-1.3.1/css/select.bootstrap4.min.css' %}">

    <script src="{% static 'traitement_app/DataTables/DataTables-1.10.20/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'traitement_app/DataTables/DataTables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'traitement_app/DataTables/Select-1.3.1/js/dataTables.select.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'traitement_app/select2.min.css' %}">
    <script src="{% static 'traitement_app/select2.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'traitement_app/print.min.css' %}">
    <script src="{% static 'traitement_app/print.min.js' %}"></script>

    <script>
        function openAttachment() {
            document.getElementById('attachment').click();
        }
    
        function encodeImageFileAsURL(element) {
            var file = element.files[0];
            var reader = new FileReader();
            reader.onloadend = function() {
                $.ajax({
                type: 'POST',
                url: "{% url 'traitement_app:index'%}",
                data: {
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    img_data: reader.result.split(',')[1],
                },
                success: function (response) {
                    location.replace("/image");
                },
                error: function (response) {
                    swal("Erreur!", "Une erreur s'est produite.", "error");
                }
            });
            }
            reader.readAsDataURL(file);
        }
    </script>
{% block script %}{% endblock %}


</head>
<body>
{% csrf_token %}
{% block sidebar %}
<div class="sidenav">
  
 <a class=" mx-auto btn btn-light" href="#" onclick="openAttachment()"  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Charger une image
 </a>
 <a class="mx-auto my-5 btn btn-light" href="{% url 'traitement_app:ResNet101' %} " role="button">Detecter</a>


</div>
<input type="file" class="file" id="attachment" style="display: none;" onchange="encodeImageFileAsURL(this)" accept=".jpg, .jpeg, .png"/>
{% endblock %}

<div class="main">

 <div class="field_set">
  <h2 >Detection d'objets presents dans une image</h2>
 </div>

  
  
  <div>
  {% block main %}
	
  {% endblock %}
  </div>
  
</div>
   
</body>
</html> 

traitement_app/templates/traitement_app/images.html
{% extends "traitement_app/base3.html" %}

{% block title %}Image{% endblock %}
{% load static %}
{% block style %}
<style>
    .displayed {
    display: block;
    margin-left: auto;
    margin-right: auto }
</style>
{% endblock %}

{% block script %}

{% endblock %}

{% block main %}
<div class="container-fluid" style="margin-top: 50px; margin-bottom: 100px; display: block;margin-left: auto;">
    <img class="displayed" src="{% static 'traitement_app/images/image.png' %}">
</div>
{% endblock %}

traitement_app/templates/traitement_app/index.html
{% extends "traitement_app/base3.html" %}

{% block title %}Index{% endblock %}

{% block style %}
<style>
    
</style>
{% endblock %}

{% block script %}

{% endblock %}

{% block main %}
<div class="container-fluid" style="margin-top: 50px; margin-bottom: 100px;">
    
</div>
{% endblock %}

traitement_app/templates/traitement_app/sideBar2.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    

<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 265px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #33FFC3;
  overflow-x: hidden;
  padding-top: 200px;
}
.sidenav2 {
  height: 100%;
  width: 265px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #33FFC3;
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #0D5054;
}
.field_set {
    margin-top: 20px;
    border: 2px black solid;
    padding: 4px;
	text-align: center;
}

.main {
  margin-left: 265px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
{% block style %}{% endblock %}

<link rel="stylesheet" type="text/css" href="{% static 'traitement_app/bootstrap-4.0.0-dist/css/bootstrap.min.css' %}">
    <script src="{% static 'traitement_app/jquery.min.js' %}"></script>
    <script src="{% static 'traitement_app/popper.min.js' %}"></script>
    <script src="{% static 'traitement_app/bootstrap-4.0.0-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'traitement_app/moment.min.js' %}"></script>
    <script src="{% static 'traitement_app/sweetalert.min.js' %}"></script>

    <link rel="stylesheet" type="text/css"
        href="{% static 'traitement_app/DataTables/DataTables-1.10.20/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css"
        href="{% static 'traitement_app/DataTables/Select-1.3.1/css/select.bootstrap4.min.css' %}">

    <script src="{% static 'traitement_app/DataTables/DataTables-1.10.20/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'traitement_app/DataTables/DataTables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'traitement_app/DataTables/Select-1.3.1/js/dataTables.select.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'traitement_app/select2.min.css' %}">
    <script src="{% static 'traitement_app/select2.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'traitement_app/print.min.css' %}">
    <script src="{% static 'traitement_app/print.min.js' %}"></script>

    <script>
        function openAttachment() {
            document.getElementById('attachment').click();
        }
    
        function encodeImageFileAsURL(element) {
            var file = element.files[0];
            var reader = new FileReader();
            reader.onloadend = function() {
                $.ajax({
                type: 'POST',
                url: "{% url 'traitement_app:index'%}",
                data: {
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    img_data: reader.result.split(',')[1],
                },
                success: function (response) {
                    location.replace("/image");
                },
                error: function (response) {
                    swal("Erreur!", "Une erreur s'est produite.", "error");
                }
            });
            }
            reader.readAsDataURL(file);
        }
    </script>
{% block script %}{% endblock %}


</head>
<body>
{% csrf_token %}
{% block sidebar %}
<div class="sidenav">
  
 <a class="nav-link dropdown-toggle" href="#" onclick="openAttachment()" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Charger une image
 </a>
 <a class="nav-link dropdown-toggle" href="{% url 'traitement_app:ResNet101' %} " role="button">Detecter</a>
 
</div>
<input type="file" class="file" id="attachment" style="display: none;" onchange="encodeImageFileAsURL(this)" accept=".jpg, .jpeg, .png"/>
{% endblock %}

<div class="main">
  <div class="field_set">
  <h2 >Detection d'objets presents dans une images</h2>
 </div>
  
  <div>
  {% block main %}
	
  {% endblock %}
  </div>
 
</div>
   
</body>
</html> 